# Generated by Django 3.1.1 on 2021-06-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_detail',
            field=models.TextField(default=False, max_length=500),
        ),
    ]
