# Generated by Django 3.1.1 on 2021-06-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0002_todo_task_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=False),
        ),
    ]
