# Generated by Django 3.1.1 on 2021-06-07 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0005_auto_20210607_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 7, 20, 53, 667813, tzinfo=utc)),
        ),
    ]
