# Generated by Django 3.1.1 on 2021-06-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0006_auto_20210607_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
